import { createHash, randomInt, timingSafeEqual } from "node:crypto";

export const PASSWORD_MAX_LENGTH = 200;

// 128 distinct, concrete, neutral lowercase words, each 4-7 letters. No
// brand, no name, nothing that could read as an insult — see
// docs/adr/0011-growing-delay-for-wrong-passwords.md for why that entropy is
// enough. suggestPassword() below combines three of them plus a number.
export const WORDS = Object.freeze([
  "acorn",
  "amber",
  "anchor",
  "apple",
  "arrow",
  "aspen",
  "autumn",
  "badge",
  "barn",
  "basin",
  "beacon",
  "beam",
  "birch",
  "bison",
  "bloom",
  "blue",
  "boat",
  "branch",
  "brass",
  "breeze",
  "bridge",
  "brook",
  "canal",
  "canyon",
  "cedar",
  "chalk",
  "cherry",
  "chip",
  "cider",
  "cliff",
  "cloud",
  "clover",
  "coast",
  "comet",
  "coral",
  "cove",
  "crane",
  "creek",
  "crest",
  "crow",
  "crown",
  "cypress",
  "dawn",
  "delta",
  "desert",
  "dove",
  "drift",
  "dune",
  "eagle",
  "ember",
  "falcon",
  "fern",
  "field",
  "finch",
  "fjord",
  "flame",
  "flint",
  "forest",
  "garden",
  "glacier",
  "glade",
  "glen",
  "grain",
  "granite",
  "grove",
  "gull",
  "harbor",
  "hazel",
  "heron",
  "hill",
  "holly",
  "hollow",
  "ivory",
  "jade",
  "juniper",
  "kelp",
  "kestrel",
  "lagoon",
  "lake",
  "lantern",
  "larch",
  "lark",
  "leaf",
  "ledge",
  "lily",
  "linen",
  "lotus",
  "lynx",
  "maple",
  "marsh",
  "meadow",
  "mesa",
  "mist",
  "moss",
  "oasis",
  "olive",
  "opal",
  "orchard",
  "otter",
  "peak",
  "pearl",
  "pebble",
  "pine",
  "plain",
  "plum",
  "pond",
  "poplar",
  "quail",
  "quartz",
  "quill",
  "raven",
  "reed",
  "ridge",
  "river",
  "robin",
  "rowan",
  "sage",
  "sand",
  "shale",
  "shore",
  "slate",
  "sparrow",
  "spring",
  "spruce",
  "stone",
  "stork",
  "stream",
  "summit",
]);

function sha256(value) {
  return createHash("sha256").update(value, "utf8").digest();
}

export function suggestPassword() {
  const parts = [
    WORDS[randomInt(0, WORDS.length)],
    WORDS[randomInt(0, WORDS.length)],
    WORDS[randomInt(0, WORDS.length)],
  ];
  const n = randomInt(100, 1000);
  return `${parts.join("-")}-${n}`;
}

export function passwordMatches(given, stored) {
  if (typeof given !== "string" || given === "") return false;
  if (typeof stored !== "string" || stored === "") return false;
  return timingSafeEqual(sha256(given), sha256(stored));
}
